### ISSUE TITLE
Update-Mechanism not working when changing image-version

### ISSUE THREAD

**Issue by lukashartl** [southalc/podman#11]
First of all, thank you very much for spending the time to create and maintain a puppet module for Podman. I really appreciate the effort you put into this.

I am already using it for rootless-container deployment and I found something I wanted to share with you.

When I create a container from some image and give it a static version like: `myrandomcontainer:1.3` and do a puppet run, it get's correctly set up. But when I change the image to `myrandomcontainer:1.4` in my puppet code it **does not get updated**.

If I would have used `:latest` and the latest-tag would get updated it would automatically upgrade the container as intended. So this case would work, but I prefer version-pinning in production environment for reproducibility.

I searched for the relevant part in the code, which is this one:

https://github.com/southalc/podman/blob/380bebba6212eb9ab6d7d829dd6928da08e99c00/manifests/container.pp#L168-L191

For your update mechanism you only compare the hash of the local image with the hash of the same image in the container registry. This means if I change the the image in my puppet config it would still compare it with the old image tag that is set in the container config on the machine. So even if I replace the puppet code with `myrandomcontainer:1.4` it would still check whether the local `myrandomcontainer:1.3` is the same as `myrandomcontainer:1.3` in the container registry.

My question would now be whether this is your intended behavior.
If not I would also be willing to provide a Pull-Request with a fix for this.

**Comment by southalc** [comment]
Thanks for the feedback and for clearly explaining the issue.  This is not intended behavior, just poor implementation.  My goal was to allow automatic updates, but I didn't consider switching out a declared version.  I'll work on a solution and release an update.  If you have already written something that works I'd welcome a pull request.

**Comment by southalc** [comment]
Version 0.2.5 of the module addresses this issue.  With the container "update" parameter as false, the container will be redeployed when the resource image parameter is changed.

**Comment by lukashartl** [comment]
The fix provided by you makes it possible to change the image when update is set to false. I created a pr for the same problem, but when update is set to true. see #13
