### ISSUE TITLE
Compilation tests fail due to unknown variable 'requires' in container.pp

### ISSUE THREAD

**Issue by toreanderson** [southalc/podman#12]
My spec tests for a class including `podman` fail:

```
  1) role::sflow on debian-8-x86_64 Debian is expected to compile into a catalogue without dependency cycles
     Failure/Error: it { should compile.with_all_deps }
       error during compilation: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: 'requires'. (file: /home/test/env/modules/podman/manifests/container.pp, line: 162, column: 21) (file: /home/test/env/design/profile/manifests/sfacctd_tee.pp, line: 4) on node 8b31bfdca048.home
     # ./spec/classes/role__sflow_spec.rb:9:in `block (4 levels) in <top (required)>'
```
The variable in questions is, as far as I can tell, only declared here: https://github.com/southalc/podman/blob/380bebba6212eb9ab6d7d829dd6928da08e99c00/manifests/container.pp#L107-L110

This declaration is enclosed in the following block: https://github.com/southalc/podman/blob/380bebba6212eb9ab6d7d829dd6928da08e99c00/manifests/container.pp#L89-L90

The variable is being referenced in several places outside of that block, however. I believe this is what trips up the tests.

**Comment by southalc** [comment]
I believe the issue is due to the $requires variable being set only when a user is defined.  I recently release an update and defined $requires on the else side of that if statement.  Does this help your unit tests?  I'm interested in adding rspec tests to the module, and would be interested if you'd submit a pull request if you have written some?  Thanks

**Comment by toreanderson** [comment]
I can confirm latest Git master fixes the problem, thanks!

As for the spec test that failed, it is isn't for the `podman` module itself, but for a class I wrote that includes it. The test in question is simply:

```
require 'spec_helper'

describe 'role::sflow' do
  on_supported_os.each do |os, facts|

    context "on #{os} #{facts[:osfamily]}" do
      let(:facts) { facts }

      it { should compile.with_all_deps }
    end

  end
end
```

Not sure if that this is useful to you.
