### ISSUE TITLE
[0.5.4] Start of rootless container fails

### ISSUE THREAD

**Issue by tuxmaster5000** [southalc/podman#33]
OS: CentOS8 Stream
When I to it via the command line, it will work:
`sudo -u <NonRootUser> -- podman container create  --name 'foo' ....`
But do the same with puppet false.
```
podman::container { 'foo':
      image => ...,
      user  => <NonRootUser>,
      flags => {
       ....
      }
```
error:
Notice: /Stage[main]/...::Container[foo]/Exec[podman_NonRootUser_Container]/returns: time="2022-01-21T10:30:36+01:00" level=error msg="XDG_RUNTIME_DIR directory \"/run/user/\" is not owned by the current user"

I thing also the unless part of:
podman/manifests/container.pp 273 fails.
because an 
`sudo -u <NonRootUser> -- podman container exists 'foo'`
will return 0

**Comment by tuxmaster5000** [comment]
The same will happens with podman::image

**Comment by tuxmaster5000** [comment]
After add some debug code in your manifests, I found the problem.
When the system option of the user resource is set to true,  then Puppet don't care about the uid. 
So that part of the code fails:
`  "XDG_RUNTIME_DIR=/run/user/${User[$user]['uid']}",`
Sample resource:
```
group { 'foo': system => true }
user { 'foo':
  system => true,
  gid  => foo,
  shell => '/sbin/nologin',
  require => Group['foo']
}
```
When set an hard uid in the user resource, then it will work.
Sample:
```
group { 'foo': system => true }
user { 'foo':
  uid => 400,
  gid  => foo,
  shell => '/sbin/nologin',
  require => Group['foo']
}
```
But setting an hart uid, can be problematic, because the uid can used by other applications on the system.

**Comment by southalc** [comment]
What you've described is the documented behavior:  https://github.com/southalc/podman/blob/master/REFERENCE.md#user

I'm open to suggestions for improvements.

**Comment by tuxmaster5000** [comment]
I think, it will be better, to get the uid from an function than from the variable.
This will work in any case. So only an function is needed, which call "id -u $user[name]" then the uid  is returned always.

**Comment by southalc** [comment]
A function would work, but it would need to be a deferred function in order to run on the agent instead of the master.  Also, since deferred functions require puppet version 6 or later we would no longer support older agents.  For the time being, I'm going to stay with the current design.
