### ISSUE TITLE
Unable to set the "--new" option when the systemd unit will be created. 

### ISSUE THREAD

**Issue by tuxmaster5000** [southalc/podman#54]
To let the podman auto update work, the "--new" option must be used:
See: https://docs.podman.io/en/latest/markdown/podman-auto-update.1.html
But when I try it with:
```
service_flags => {
        'new' => ''
}
```
It will fails with:
```
returns: Error: accepts 1 arg(s), received 2
Failed to call refresh: 'podman generate systemd  --new '' foo 
```

**Comment by southalc** [comment]
I fixed this issue in new version 0.6.4, but please note that the module has a built-in method for updating containers that pre-dates the podman auto-update functionality.  I haven't tested this, but would suggest if you opt to use podman auto-update to also set the "update" parameter of those puppet "podman::container" instances to false.
