### ISSUE TITLE
Warning: This function is deprecated, please use stdlib::merge instead

### ISSUE THREAD

**Issue by ZaxLofful** [southalc/podman#68]
When I use this module I am current getting a warning:

Warning: This function is deprecated, please use stdlib::merge instead. at ["/opt/user/modules/podman/manifests/container.pp", 97]:
   (location: /opt/user/modules/stdlib/lib/puppet/functions/deprecation.rb:35:in `deprecation')

**Comment by southalc** [comment]
This fix is now committed.
