### ISSUE TITLE
podman networks created after containers - which then fails

### ISSUE THREAD

**Issue by Enrice** [southalc/podman#78]
When I create everything by parameterizing the class, container creation fails because of missing network definition.

I think the order of creation should be swapped here.

**Comment by Enrice** [comment]
Ok I can see the problem:
My VERY old podman installation (podman 1.6.4 which is the one we have in CentOS 7) does not know the command "podman network exists", but I found that I could also use "podman network inspect". Would this be feasible to be downwards compatible?

**Comment by jonesbrennan** [comment]
I have run into this issue as well where the networks get created after the containers. I am passing the --net flag to podman container create in the container class but the network doesn't exist yet.

**Comment by jonesbrennan** [comment]
I have created https://github.com/southalc/podman/pull/85 for this issue.

**Comment by southalc** [comment]
I've updated the ordering of resources in the module, but it's probably still best to explicitly declare dependencies with "notify" or "require"
