### ISSUE TITLE
Consider tagging releases in Git

### ISSUE THREAD

**Issue by toreanderson** [southalc/podman#8]
It would be nice if the numbered releases of this module (and https://github.com/southalc/types for that matter) were tagged with `git-tag(1)`, so that specific versions of the module can be installed by setting `:ref` or `:tag` in `Puppetfile` to refer to the desired version.

This is helpful when corporate policy do not allow the build infrastructure to have dependencies on third-party services (such as Puppet Forge and GitHub). To that end we mirror the upstream Git repos of all the Puppet modules we use to an on-prem GitLab instance, and point `Puppetfile` at those mirrors using `:git`.

**Comment by southalc** [comment]
I had not used git tags before, but added them to the most recent releases of podman and types.  Thanks
