### ISSUE TITLE
Add ability to generate quadlet podman-systemd units

### ISSUE THREAD

**Issue by yachub** [southalc/podman#82]
Since `podman systemd generate` is [deprecated](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html) we should add an option to create [quadlet](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html) podman-systemd units, which was added in Podman [v4.4.0](https://github.com/containers/podman/releases/tag/v4.4.0), via something like [podlet](https://github.com/k9withabone/podlet).

**Comment by yachub** [comment]
Ah sorry just realized this is a duplicate of https://github.com/southalc/podman/issues/76

**Comment by traylenator** [comment]
See #83 as start.

**Comment by southalc** [comment]
Version 0.7.0 includes quadlet support.  There's a forked project with another implementation here if you're interested:
https://github.com/voxpupuli/puppet-quadlets
