### ISSUE TITLE
Southalc podman module doesn't enable service

### ISSUE THREAD

**Issue by ultrapain1** [southalc/podman#86]
From the podman v0.6.7 module on forge.puppet.com:

enable
Data type: Boolean

Status of the automatically generated systemd service for the container. Valid values are 'running' or 'stopped'.

Default value: true

There is an issue with the code in container.pp.  The variable $service_unit_file is defined as:
${User[$user]['home']}/.config.systemd/user/podman-${container_name}.service

In this code block, you don't specify the full path of the service:
$command_sp @("END"/L)
  ${systemctl} ${startup} podman-${container_name}.service
  ${systemctl} ${action} podman-${container_name}.service
  | END

This code should be changed to:
${systemctl} ${startup} ${service_unit_file}

**Comment by breca** [comment]
Hey, I'm using `v0.6.7` (the latest release) in my environment. I can't say I've encountered this issue myself.

I'd expect this sort of thing could happen if a `daemon-reload` was somehow not executed?

Relevant sections
https://github.com/southalc/podman/blob/0.6.7/manifests/container.pp#L101-L157
https://github.com/southalc/podman/blob/0.6.7/manifests/container.pp#L300-L343

Could you share more details about the your environment and the specific issue you're having? (Debug logs might be good)

**Comment by southalc** [comment]
This has also been working for me, so I'm gonna close the issue.  If you're still having issues with user containers, try the quadlet type
