### ISSUE TITLE
Upgraded to Podman 5.x on AlmaLinux 9.5 and now every container changes on every run

### ISSUE THREAD

**Issue by reyjrar** [southalc/podman#91]
Previously, if the running container image was up-to-date, the image would not be pulled. Now, with podman 5.x on AlmaLinux 9.5, every run of puppet causes **EVERY** `podman::container` to refresh.

I'm still firefighting a ton of podman issues, so I haven't had as much time to try to debug this.

**Comment by optiz0r** [comment]
Seeing the same. This module is using `skopeo inspect docker://<image> | /opt/puppetlabs/puppet/bin/ruby -rjson -e 'puts (JSON.parse(STDIN.read))["Digest"]'` to identify the hash of the latest image in the repository, and `podman image inspect docker.io/<image> --format '{{.Digest}}'. The two hashes differ.

The has produced by podman inspect matches the hash visible in docker hub webui. Not sure where skopeo is getting its digest from as yet.

**Comment by toreanderson** [comment]
I still get the spurious restart after upgrading to 0.7.5. I believe this is related to the verification of the flags. One of the containers impacted by the problem has the following flags:

```puppet
{
      net    => 'host',
      volume => 'caddy:/data/caddy',
}
```

When this is base64-encoded and stored into `$flags_base64`, the value is `eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHkifQ==`. This happens here: https://github.com/southalc/podman/blob/d6a0be38704d645a588b979601554012276fabd6/manifests/container.pp#L89

This is the compared with the output from `podman container inspect caddy --format '{{.Config.Labels.puppet_resource_flags}}'` to check for changes here: https://github.com/southalc/podman/blob/d6a0be38704d645a588b979601554012276fabd6/manifests/container.pp#L165-L168

The problem appears to be that the latter command contains a newline character:

```shell
$ podman container inspect caddy --format '{{.Config.Labels.puppet_resource_flags}}'
eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHki
fQ==
$ podman container inspect caddy | grep puppet_resource_flags
                    "puppet_resource_flags": "eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHki\nfQ=="
                    "puppet_resource_flags=eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHki\nfQ==",
```

This newline character does not appear in `$flags_base64`. Therefore the equality test fails, and the module proceeds with tearing down the container and re-creating it from scratch.

One way around this might be to decode the base64 flags before comparing them, as the decoded content is in fact identical:

```shell
$  podman container inspect caddy --format '{{.Config.Labels.puppet_resource_flags}}' | base64 -d | md5sum
7efa2977335f8792992ef3bd44adcf35  -
$ echo eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHkifQ== | base64 -d | md5sum
7efa2977335f8792992ef3bd44adcf35  -
```

**Comment by toreanderson** [comment]
I have so far been unable to figure out what causes this newline to appear in the first place.. When I manually create a container with that label, it does not appear:

```console
$ podman container create --label puppet_resource_flags=eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHkifQ== docker.io/library/caddy:2
0671e829c86e450f3f17d8ca725be67f677a7c3b4c4f6564d10cb8f63326421b
$ podman container inspect 0671e829c86e450f3f17d8ca725be67f677a7c3b4c4f6564d10cb8f63326421b --format '{{.Config.Labels.puppet_resource_flags}}'
eyJuZXQiPT4iaG9zdCIsICJ2b2x1bWUiPT4iY2FkZHk6L2RhdGEvY2FkZHkifQ==
```

**Comment by toreanderson** [comment]
Figured it out. The problem is that I am upgrading from a module version that does not contain commit 2da1228. The previous version called `base64()` in a way that makes it insert newlines every 60 characters (cf. https://ruby-doc.org/stdlib-2.5.0/libdoc/base64/rdoc/Base64.html), while versions after 2da1228 don't.

The workaround appears to be to first upgrade, then stop and **_delete_** (important!) all containers managed by the module and then run Puppet - at which point the containers will be recreated with a `puppet_resource_flags` label that no longer contain newlines. Subsequent Puppet runs will then no longer cause spurious container restarts.
