### ISSUE TITLE
Any changes to flags does not take place in container as the same container gets restarted

### ISSUE THREAD

**Issue by utkarsh-jain-ghp** [southalc/podman#93]
This looks like a bug in podman::container class where, if there are any changes made to flags, the container does not get recreated but just restarted and hence every puppet run just refreshes the same container.

It might be due to, https://github.com/southalc/podman/blob/d6a0be38704d645a588b979601554012276fabd6/manifests/container.pp#L252

```
$onlyif_prc = @("END"/L)
        test $(podmain container inspect --format json ${container_name} |\
        ${_ruby} -rjson -e 'puts (JSON.parse(STDIN.read))[0]["State"]["Running"]') = 
        | END
```

**Comment by southalc** [comment]
Closed since merging #94 .  Thanks for your help.
